Remove superuser-related docs for supabase
snaplet/docs-old pull request #119
Opened 2022-11-02 14:31 UTC by justinvdm

On Nov 5, users will not be able to be superusers on supabase anymore: https://github.com/supabase/supabase/discussions/9314. We should merge this docs change _on Nov 5_.

2022-11-02 14:38 UTC, jgoux requested changes
Formatting details and a question about the `postgres` role. :)

2022-11-02 14:38 UTC, jgoux commented on docs/06-tutorials/supabase-clone-environments.md
>  You’ll then have to confirm providing Snaplet access to your database. Snaplet will prompt you to only provide `read-only` access to your database. We have a guide in our documentation on how to go a
We need to update this guide to add the `BYPASSRLS` role

2022-11-02 14:38 UTC, jgoux commented on docs/06-tutorials/supabase-clone-environments.md
> -### Step 5: Make your `postgres` user a superuser
Should we say that for restoring, they **must** use the `postgres` role?

Also now that this step is deleted we should decrement the number of the next steps to 5 and 6. 👍

2022-11-03 11:07 UTC, justinvdm commented on docs/06-tutorials/supabase-clone-environments.md
>  You’ll then have to confirm providing Snaplet access to your database. Snaplet will prompt you to only provide `read-only` access to your database. We have a guide in our documentation on how to go a
That'd only be needed once we make that change to the introspection queries though, right? Or do you just mean we should do this ahead of time?

2022-11-03 11:07 UTC, justinvdm commented on docs/06-tutorials/supabase-clone-environments.md
> -### Step 5: Make your `postgres` user a superuser
:+1: and :+1:, thank you!

2022-11-03 11:33 UTC, jgoux commented on docs/06-tutorials/supabase-clone-environments.md
>  You’ll then have to confirm providing Snaplet access to your database. Snaplet will prompt you to only provide `read-only` access to your database. We have a guide in our documentation on how to go a
It should always be applied, right now if a user uses RLS rules we won't bring the matching rows into the snapshots.

2022-11-03 11:39 UTC, justinvdm commented
@jgoux thanks for the review! Could you take another look when you have a moment?

2022-11-03 11:46 UTC, jgoux approved these changes
Looks good to me, did you try executing the `BYPASSRLS` statement?

Good job!

2022-11-03 12:04 UTC, justinvdm commented
> Looks good to me, did you try executing the `BYPASSRLS` statement?
> 
> Good job!

Looks like it worked :) only via psql, not via the SQL editor, I'll note that in the docs

2022-11-03 12:10 UTC, justinvdm commented
Thanks for the review @jgoux :) I'll keep this open until November 5, at which point we should merge. Heads up on this @peterp.

2022-11-03 12:15 UTC, justinvdm commented
On second thought, merging - people have had a month already to migrate. We might just need to tell people to migrate.

2022-11-03 12:15 UTC, merged